
INSERT INTO Course (deptId, crsCode, crsName)
	VALUES ('MGT', 'MGT381', 'Fundamental Programming Concepts Summer 18 (ITH) CR Summer 19 (ITH) CR Summer 20 (ITH) CR'),
			('MAT', 'MAT796', 'Introduction to Computing Using Python Spring 20 (ITH) CR Summer 20 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT112', 'Introduction to Computing Using MATLAB Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT523', 'Short Course in MATLAB Spring 19 (ITH) CR Fall 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE952', 'Short Course in Python Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS663', 'Introductory Design and Programming for the Web Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT659', 'Choices and Consequences in Computing Not Offered Recently'),
			('EE', 'EE142', 'Data Science for All Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MAT', 'MAT615', 'Computing in the Arts Summer 18 (ITH) CR Summer 19 (ITH) CR Summer 20 (ITH) CR'),
			('MAT', 'MAT459', 'Visual Imaging in the Electronic Age Fall 17 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE249', 'Introduction to Cognitive Science Summer 19 (ITH) CR Spring 20 (ITH) CR Summer 20 (ITH) CR'),
			('EE', 'EE712', 'Freshmen and Nontechnical Team Projects Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE507', 'C++ Programming Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT912', 'UNIX Tools and Scripting Spring 17 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE820', 'Object-Oriented Programming and Data Structures Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT962', 'Programming Practicum Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE850', 'Object-Oriented Design and Data Structures - Honors Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT650', 'Intermediate Design and Programming for the Web Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS622', 'Urban Analytics Fall 20 (ITH) CR'),
			('MAT', 'MAT203', 'Excursions in Computational Sustainability Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS371', 'Discrete Structures Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT406', 'Discrete Structures - Honors Spring 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE481', 'Networks Fall 17 (ITH) CR Fall 18 (ITH) CR Fall 19 (ITH) CR'),
			('EE', 'EE860', 'Data Structures and Functional Programming Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT674', 'Introduction to Computer Game Architecture Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT382', 'Computational Mathematics for Computer Science Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT649', 'Data-Driven Web Applications Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT158', 'Computer System Organization and Programming Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS612', 'Embedded Systems Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT142', 'Autonomous Mobile Robots Spring 17 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS314', 'Teaching Experience in Computer Science Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE676', 'Programming Languages and Logics Fall 16 (ITH) CR Fall 18 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE308', 'Introduction to Compilers Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT794', 'Practicum in Compilers Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS327', 'Advanced Topics in Computer Game Architecture Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS399', 'Formal Verification Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT884', 'Numerical Analysis and Differential Equations Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT825', 'Numerical Analysis: Linear and Nonlinear Problems Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MAT', 'MAT659', 'Language and Information Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT830', 'Introduction to Database Systems Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT954', 'Practicum in Database Systems Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT597', 'Operating Systems Spring 20 (ITH) CR Summer 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT976', 'Practicum in Operating Systems Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT755', 'Systems Programming Fall 20 (ITH) CR'),
			('EE', 'EE155', 'Computer Architecture Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE351', 'Introduction to Computer Networks Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT563', 'Introduction to Computer Graphics Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS982', 'Computer Graphics Practicum Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS684', 'Introduction to Computer Vision Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MAT', 'MAT423', 'Foundations of Artificial Intelligence Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE179', 'Practicum in Artificial Intelligence Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE509', 'Natural Language Processing Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE413', 'Computational Linguistics Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT157', 'Human Robot Interaction - Research and Design Spring 17 (ITH) CR Spring 19 (ITH) CR'),
			('MGT', 'MGT574', 'Computational Genetics and Genomics Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS705', 'Introduction to Machine Learning Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE719', 'Machine Learning for Data Science Fall 17 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS739', 'Principles of Large-Scale Machine Learning Systems Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS581', 'Introduction to Theory of Computing Fall 17 (ITH) CR Fall 18 (ITH) CR Fall 19 (ITH) CR'),
			('MAT', 'MAT807', 'Quantum Information Processing Fall 16 (ITH) CR Fall 18 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT409', 'Introduction to Computational Complexity Spring 20 (ITH) CR'),
			('EE', 'EE482', 'Introduction to Analysis of Algorithms Spring 20 (ITH) CR Summer 20 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT382', 'Introduction to Cryptography Spring 17 (ITH) CR'),
			('EE', 'EE228', 'Mathematical Foundations for the Information Age Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE971', 'Networks II: Market Design Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE119', 'Applied Logic Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS856', 'International Research Internship Spring 19 (ITH) CR Summer 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE282', 'Practical Training in Computer Science Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT225', 'Team Projects Fall 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT619', 'Independent Reading and Research Spring 20 (ITH) CR Summer 20 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS954', 'Introduction to Blockchains, Cryptocurrencies, and Smart Contracts Spring 17 (NYC) CR Spring 18 (NYC) CR'),
			('MAT', 'MAT768', 'Programming Languages and Logics Fall 16 (ITH) CR Fall 18 (ITH) CR Fall 20 (ITH) CR'),
			('MAT', 'MAT365', 'Algorithms and Data Structures for Applications Fall 18 (NYC) CR Fall 19 (NYC) CR Fall 20 (NYC) CR'),
			('MGT', 'MGT157', 'Network Programming Languages Fall 17 (ITH) CR Fall 18 (ITH) CR Fall 19 (ITH) CR'),
			('MAT', 'MAT561', 'Introduction to Compilers Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('MAT', 'MAT793', 'Practicum in Compilers Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS315', 'Software Engineering Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE177', 'Open-Source Software Engineering Spring 17 (ITH) CR Spring 19 (ITH) CR Fall 19 (ITH) CR'),
			('CS', 'CS762', 'Competition Programming and Problem Solving Seminar Spring 19 (ITH) CR Fall 19 (ITH) CR Spring 20 (ITH) CR'),
			('MGT', 'MGT247', 'Applications of Parallel Computers Fall 17 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE652', 'Data Science in the Wild Spring 19 (NYC) CR Spring 20 (NYC) CR Fall 20 (NYC) CR'),
			('MGT', 'MGT716', 'Crowdsourcing and Human Computation Fall 17 (ITH) CR Fall 18 (ITH) CR Fall 19 (ITH) CR'),
			('CS', 'CS854', 'Introduction to Database Systems Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE239', 'Practicum in Database Systems Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE337', 'Startup Systems Design and Engineering Fall 16 (NYC) CR Fall 17 (NYC) CR'),
			('CS', 'CS807', 'Cloud Computing Spring 18 (ITH) CR Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('CS', 'CS359', 'Distributed Computing Principles Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS665', 'Advanced Computer Architecture Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS923', 'Developing and Designing Interactive Devices Fall 18 (NYC) CR Fall 19 (NYC) CR Fall 20 (NYC) CR'),
			('EE', 'EE820', 'System Security Spring 19 (ITH) CR Spring 20 (ITH) CR Fall 20 (ITH) CR'),
			('CS', 'CS735', 'Practicum in System Security Spring 17 (ITH) CR Spring 18 (ITH) CR Spring 19 (ITH) CR Not Offered Spring 20'),
			('EE', 'EE639', 'Blockchains, Cryptocurrencies, and Smart Contracts Spring 18 (NYC) CR Spring 19 (NYC) CR Spring 20 (NYC) CR'),
			('CS', 'CS262', 'Security and Privacy Concepts in the Wild Fall 18 (NYC) CR Fall 19 (NYC) CR Fall 20 (NYC) CR'),
			('EE', 'EE988', 'Privacy in the Digital Age Spring 17 (NYC) CR Spring 18 (NYC) CR'),
			('MAT', 'MAT141', 'Practicum in Computer Security Fall 18 (NYC) CR'),
			('EE', 'EE287', 'Networked and Distributed Systems Fall 17 (NYC) CR Fall 18 (NYC) CR Spring 20 (NYC) CR'),
			('MAT', 'MAT369', 'Introduction to Computer Graphics Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('EE', 'EE964', 'Computer Graphics Practicum Fall 18 (ITH) CR Fall 19 (ITH) CR Fall 20 (ITH) CR'),
			('MGT', 'MGT989', 'Interactive Computer Graphics Spring 19 (ITH) CR Spring 20 (ITH) CR'),
			('EE', 'EE615', 'Virtual and Augmented Reality Fall 18 (NYC) CR Fall 19 (NYC) CR Fall 20 (NYC) CR');
