# docker-compose.yml
version: "3"
services:
    detector:
        build: ./detector
        environment:
          KAFKA_BROKER_URL: broker:9092
          TRANSACTIONS_TOPIC: queueing.transactions

# Give this composition access to the Kafka network
networks:
  default:
    external:
       name: kafka-network
